import { useTheme } from 'styled-components';
import NextHead from 'next/head';

const Head: React.FC = () => {
  const currentTheme = useTheme();
  return (
    <>
      <NextHead>
        <title>Create Next App</title>
        <meta name='theme-color' content={ currentTheme.backgroundColor } />
        <meta name='description' content='Generated by create next app' />
        <link rel='shortcut icon' href='/favicon.ico' />
      </NextHead>
    </>
  );
};

export default Head;
